module.exports = {
  PERMISSIONS: {
    VIEW_DASHBOARD: 'view_dashboard',
    CREATE_SALE: 'create_sale',
    VIEW_SALES: 'view_sales',
    CANCEL_SALE: 'cancel_sale',
    MANAGE_PRODUCTS: 'manage_products',
    VIEW_PRODUCTS: 'view_products',
    MANAGE_INVENTORY: 'manage_inventory',
    VIEW_INVENTORY: 'view_inventory',
    MANAGE_CUSTOMERS: 'manage_customers',
    VIEW_CUSTOMERS: 'view_customers',
    MANAGE_DEBTORS: 'manage_debtors',
    VIEW_DEBTORS: 'view_debtors',
    MANAGE_EXPENSES: 'manage_expenses',
    VIEW_EXPENSES: 'view_expenses',
    VIEW_REPORTS: 'view_reports',
    VIEW_FINANCIALS: 'view_financials',
    MANAGE_USERS: 'manage_users',
    MANAGE_SETTINGS: 'manage_settings',
    MANAGE_PARTNERS: 'manage_partners',
  },
  DEFAULT_ROLES: {
    OWNER: 'Owner',
    MANAGER: 'Manager',
    CASHIER: 'Cashier',
    ACCOUNTANT: 'Accountant',
  },
  PAYMENT_METHODS: ['cash', 'mpesa', 'bank', 'card', 'credit', 'other'],
  SALE_STATUSES: ['pending', 'completed', 'cancelled', 'overdue'],
};